### PR TITLE
Ignore alternate stylesheets

### PR DESCRIPTION
**Pull request by jacobrask**
Only match `link` elements with `rel="stylesheet"`, not `stylesheet alternate`, etc.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi, thanks for the fix!
Some comments:
- You don't need the parentheses in `(\s+)`. Also, since you're using attribute equality in the CSS selector, you may as well use equality there too. 
- While you're at it, you could maybe add a way of making a stylesheet opt-out, through a `data-noprefix` property. What do you think? :)

**Comment by jacobrask** [comment]
Good ideas, take a look at this attempt. I didn't know which minifier your prefer, so I did a separate commit for the minified file.

I am planning to use prefixfree for my CSS1K project btw. I will probably remove prefixfree's style tag on each style switch and then insert a new link tag and let dynamic-dom take care of it.

**Comment by LeaVerou** [comment]
Thanks!

Sorry, one last correction (promise!): You don't need `getAttribute` to check if a property exists (which is what we care about), just use `hasAttribute`. :)

**Comment by LeaVerou** [comment]
Btw, I'd advise you use the dynamic DOM plugin if you **really** need that kind of dynamic behavior. It depends on mutation events, which are known to make browsers a bit slower. If you control the JS, you can just use the functions in StyleFix to update it, which is what I did in dabblet.

**Comment by jacobrask** [comment]
np :)

**Comment by jacobrask** [comment]
I'll take a look at the dabblet source then, thanks

**Comment by LeaVerou** [comment]
Beautiful, merged. For future reference, I usually use Google Closure Compiler for minification, but in my experience, uglify is just as good.

**Comment by johtso** [comment]
Would be great if the `data-noprefix` functionality was mentioned somewhere in the docs!

**Comment by LeaVerou** [comment]
Feel free to send a pull request :)

**Comment by johtso** [comment]
Done :) https://github.com/LeaVerou/prefixfree/pull/147

**Pull request merged**
