### PR TITLE
Adding support for grab & grabbing cursors

### PR DESCRIPTION
**Pull request by timhettler**
I needed support for these values in a prototype I'm building and noticed they were omitted. See:

https://developer.mozilla.org/en/CSS/cursor

WebKit & Mozilla both implement these values with prefixes.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you!

The code is perfect, I'm just a bit reluctant to add it since they are not in the specification and I try to only add standards-compliant stuff, with few exceptions.

I will raise the issue in www-style and ask if there are any plans to standardize them. Which browsers support these cursors?

**Comment by timhettler** [comment]
Just did some quick testing and it appears that only WebKit and Mozilla support the cursors.

**Comment by LeaVerou** [comment]
Thanks. I looked into the archives, found a discussion about them and revived it: http://lists.w3.org/Archives/Public/www-style/2012Jan/1242.html

Lets see how it goes.

**Comment by MartinMuzatko** [comment]
it's been a few years. hows the current status?

**Comment by LeaVerou** [comment]
They are in [the spec](https://drafts.csswg.org/css-ui-3/) now, so I would merge if conflicts were resolved.

**Comment by MartinMuzatko** [comment]
Awesome! great work @LeaVerou

**Comment by yckart** [comment]
Any updates on this?

**Comment by LeaVerou** [comment]
I said I would merge this if conflicts were resolved. At its current state, this PR cannot be merged. Since @timhettler clearly doesn't care about it any longer, I'd advise whoever does to send a new one. Closing this.

**Pull request closed without merging**
