### PR TITLE
Fixed problem with the disabled media-query in IE9

### PR DESCRIPTION
**Pull request by dziudek**
This commit duplicates line style.media = link.media; - the duplicated
line is necessary to work both in IE9 and other browsers

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thanks! Could you please add a short comment explaining why the line needs to be duplicated? Otherwise future devs will think it's a mistake.

**Comment by dziudek** [comment]
The code:

``` js
var style = document.createElement('style');
style.textContent = css;
style.media = link.media; // 1
style.disabled = link.disabled;
style.setAttribute('data-href', link.getAttribute('href'));

parent.insertBefore(style, link);
parent.removeChild(link);

style.media = link.media; // 2
```

contains duplicated lines marked as **// 1** and **// 2** because in the IE9 without line **// 2** IE9 loads at first time all CSS stylesheets regardles media-query rules. After adding line **// 2** the problem dissapears. It seems that IE9 needs the media attribute declaration after placement the style element to the document DOM. But the line **// 1** is still necessary, because modern browsers like Chrome don't work when only line **// 2** exists.

**Comment by LeaVerou** [comment]
LOL, I don't mean a comment here, I meant a comment in the code! :)

I can do it if it's a problem, just a bit busy right now.

**Comment by dziudek** [comment]
oh, sorry :D Could you put it to your code with link to this explanaition?

**Comment by LeaVerou** [comment]
Ok, I'll add it at some point. Pull request merged.
Btw I was just expecting something simple like `// Duplicate is intentional. See issue #31` in the 2nd line.

**Comment by dziudek** [comment]
Ok, I'll remember for the future work with the script - I've a hard monday morning today ;)

**Pull request merged**
