### PR TITLE
Remove extra double quotes at the end of background-image: url()

### PR DESCRIPTION
**Pull request by ghost**
when using double quotes for the image path

Image

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi!

Thanks for spotting the bug, but this is not the right way to fix it. The right way to fix it is to avoid matching the quotes in the first place.

**Comment by ghost** [comment]
The funny thing is that it only happens in the minified version. I'll check into it

**Comment by ghost** [comment]
OK. So it turns out that the minified version uses this regex
**/url(('?|"?)(.+?)\1)/gi**
and the uncompresed uses:
**/url(\s_?((?:"|')?)(.+?)\1\s_?)/gi**

I suggest an update of the minified version

**Comment by LeaVerou** [comment]
I guess the minified version has now been updated, so I'm closing this.

**Pull request closed without merging**
