### PR TITLE
Removing unPrefixed class from root element.

### PR DESCRIPTION
**Pull request by ramsesoriginal**
with the css rule ".unPrefixed \* { display:none;}" and setting the class unPrefixed on the root element it's now possible to hide everything from the browser as long as the stylesheets are not ready.

### CODE REVIEW

**Comment by LeaVerou** [comment]
What are the use cases for this?

**Comment by ramsesoriginal** [comment]
I am working on a website that includes a bunch of css stylesheets that can get rather large both in size (for example they include images as data urls) and number.

While the vendor-specific prefixes aren't present, the page looks rather ugly, and on slower user-agents (both in processing power and conenction speed, think for example older netbooks connected through a not-3g phone) there is enought time for someone to start inserting data into forms and clicking around on the unstyled page.Especially column-count and box-sizing can look rather bad and cause pleny of confusion.. If we add transitions (which clearly get re-evaluated when the new styles are computed, thus confusing the user even more) the site looks unacceptable for a while (not, long, but enough to be noticed by everyone).

If I could hide the affected items as long as the prefixes aren't there it would already be a big improvement.

**Comment by LeaVerou** [comment]
Are you sure you're including the script right after the stylesheets? Do you have any examples of this behavior uploaded anywhere?

**Comment by ramsesoriginal** [comment]
I'm including it right after the last stylesheet..

``` html
        <link rel='stylesheet' id='layout_stylesheet_23'  href='layout23.css'/>
        <script src="prefixfree.js"></script>
```

**Comment by LeaVerou** [comment]
But even if I add this, it won't work as expected. The unprefixed class gets added BEFORE the stylesheets get processed, just as long as the XHR requests get fired. :(

But I'd really want to look more into this, so if you could create an issue with a linked example that's that slow I might be able to look into it and improve performance.

**Pull request closed without merging**
