### PR TITLE
trigger a custom event 'StyleFixProcessed'

### PR DESCRIPTION
**Pull request by joyously**
Add a custom event 'StyleFixProcessed' to indicate when the styles are fixed.
This is needed for situations that entail further processing, such as described in #6132

### CODE REVIEW

**Comment by LeaVerou** [comment]
What about when there are multiple stylesheets, and multiple StyleFix rules? Do you fire one or more events? If one, does it fire correctly at the end?

Also, it seems you accidentally included some other changes in this PR?

**Comment by joyously** [comment]
The event is for when all of the `process` function is finished, which is after handling the multiple stylesheets and rules.
And the other changes are intentional. The event is needed for the fallback fix that I included.

**Comment by LeaVerou** [comment]
Merged, thanks.
Should I close the other PR then?

**Comment by joyously** [comment]
Yes

**Pull request merged**
