### PR TITLE
Fix bug #62: Handle various kinds of relative URLs

### PR DESCRIPTION
**Pull request by SimonSapin**
This is still not a full URL parser as in http://url.spec.whatwg.org/
but should be good enough.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Should also update prefixfree.min.js but I’m not sure how to do that.

**Comment by LeaVerou** [comment]
Hi, 

Thanks for contributing.
Which (real world) cases does the current code fail on?

**Comment by SimonSapin** [comment]
As #62 says, it fails with domain-relative URLS like `url(/img/logo.png)` when the stylesheet is not on the same domain as the document (which in turn requires the appropriate CORS headers on the stylesheet.)

**Comment by SimonSapin** [comment]
Although much less common, scheme-relative URLs like `//example.net/foo.png` can be useful when something works on both HTTP and HTTPS.

**Comment by MarkVaughn** [comment]
Just had this issue today ( #130 ) fixed tested and this fixed it, however I am not able to minimize the code without causing errors. (needs some Linting maybe?)

**Comment by LeaVerou** [comment]
Simon, were you able to minify?

**Comment by SimonSapin** [comment]
I was about to ask: how do you minify? A small “how to minify” in the README would be great.

**Comment by LeaVerou** [comment]
You can use http://closure-compiler.appspot.com/home

**Comment by SimonSapin** [comment]
Ok, minified.

**Pull request merged**
