### PR TITLE
IE9: Fallback to XDomainRequest if available.

### LINKED ISSUE #60: Support of XDomainRequest
Hi!

When doing cross-domain requests, IE8 and IE9 require to use XDomainRequest instead of XMLHttpRequest.

### PR DESCRIPTION
**Pull request by vincentbernat**
On IE9, `XMLHttpRequest` does not allow to do a crossdomain
request. An exception is triggered on `open()` in this case. We
intercept this exception and use `XDomainRequest` if available.

This should close #60.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi Vincent,

Thank you very much for your effort!

However, it would've been much better if you discussed this with me before working on it. Or at least if you searched the bug tracker archives. This has been discussed in the past, and I decided not to add XDomainRequest on purpose. My reasoning is that I don't like adding non-standard stuff if it won't enhance the experience of a significant percentage of the target audience, and since practically no developers use IE as their main browser, there isn't a strong enough case for this. Please note that for _testing_ in IE, you can use the result page which works everywhere (Cloud icon -> View full page result) or just add /result/ before /gist/ in the URL.

Hope that doesn't put you off future contributions.

Cheers,
Lea

**Comment by vincentbernat** [comment]
Hi Lea!

I didn't find anything in the issue tracker and searching again yield no sensible results (no mention of `XDomainRequest` for example). I don't have any problem with you not merging the pull request: I needed it for myself and therefore I did not waste my time (not more than usual). People having the same problem will hopefully find this pull request for a possible fix.

However, I don't quite understand why IE9 is not a good target audience: many (indirect) users of prefix free will use IE. Since it is considered to be a good practice to put static assets on a separate domain, I suppose this is not uncommon to need crossdomain requests and have IE9 users.

I must also confess that I did not understand your note about testing in IE (cloud icon? in Github? In IE? URL with /gist?).

**Comment by LeaVerou** [comment]
OMG. I'm so sorry, I thought this was a pull request for Dabblet. To my defense, I had just woken up. *embarrassed*
Reopened, will review soon.

**Comment by LeaVerou** [comment]
Hi there, sorry for the delay.

Comments:
- Please don't forget to change the minified version
- I'd prefer a better CORS detection than `try...catch`. Perhaps `'withCredentials' in xhr`? (From https://github.com/thvd/Modernizr/commit/af674f233d762d492ff777c9f4d24bf4999ad4b7 )
- Do `onerror` and `onprogress` _need_ to be set?

Apart from those, it's great. Thanks again!

**Comment by vincentbernat** [comment]
For `onerror` and `onprogress`, yes, they need to be set. IE will invoke them even when they don't exist (and nothing will happen in this case).

`XDomainRequest` cannot be used for non-crossdomain request. Therefore, the "try/catch" is there to detect if the request is a crossdomain one or not. I could check for the property `withCredentials` in `catch`. Its existence and the existence of XDomainRequest would mean that we are in a version of IE recent enough to allow one to use standard `XMLHttpRequest` for CORS. However, there is currently no such version of IE (except recent beta of IE10). It seems safer to retry the request with `XDomainRequest` if available.

How should I update the minified version? Can I just run uglifyjs on it?

**Comment by LeaVerou** [comment]
I'm wondering if there's a way to check whether it will be a cross-domain request before sending it, to avoid the `try...catch`. Of course, I could merge this in for now, and work on improving it later. Funnily enough, I ran into a case of needing this myself today :)

Yes, uglifyjs is fine for minifying. :)

Thanks!

**Comment by vincentbernat** [comment]
I have updated the pull request with the minified version.

I don't know if this is easy to parse an URL with Javascript (I think this is difficult unless you find a way to put it in `window.location` or something like that). Moreover, I remember that IE has very special rules to determine if a request is a crossdomain one or not. Something that look like a cross domain request could be a regular request because the issuer is in some trust zone. I am not specialist enough to be affirmative.

Please note that IE triggers the exception before sending anything.

**Comment by LeaVerou** [comment]
Merged! Will go live soon.

**Pull request merged**
