### PR TITLE
Add a license file

### PR DESCRIPTION
**Pull request by pygy**
There are various statements of intent in the code base, but no proper license AFAICT.

### CODE REVIEW

**Comment by pygy** [comment]
I didn't add it to the Bower ignore list because it makes sense to distribute it along with the code.

**Comment by LeaVerou** [comment]
Oops, I added a LICENSE file before seeing this, sorry! In any case, there is a license file now. :)

**Comment by pygy** [comment]
Great, thanks :-)

**Comment by pygy** [comment]
FYI, I needed this because I've written a [prefixer](https://github.com/j2css/j2c/tree/v1_preview/plugins/prefix-browser) based on PrefixFree for my CSS in JS lib. I initially intended to extract source parts and build around them, but it was too rigid so I ended up refactoring it manually.

Unlike Prefixfree which operates on full CSS source with regexps, the plugin works on a structured data stream of selectors, declarations and at-rules, and different data structures were needed.

On top of the PrefixFree feature set, it also fixes flexbox (as much as possible), `@media (resolution: 2dppx)` and a few extra selectors. The first two would be hard to backport without adding additional Regexp passes, but the extra selectors could be added with minor modifications (`::placeholder` maps to 4 different prefixed syntaxes), I can send a PR if you're interested.

I wanted to send a warm "thank you" for your work on Prefixfree. The detection techniques you've pioneered and validated were plundered almost as-is. I wouldn't have known where to begin if I hadn't had your code to rely on.

**Pull request closed without merging**
