### PR TITLE
Only modify styles, triggering reflows, if needed

### PR DESCRIPTION
**Pull request by fryn**
This change ensures that -prefix-free modifies styles, which triggers reflows, only when StyleFix.fix finds something that needs prefixing.

### CODE REVIEW

**Comment by LeaVerou** [comment]
???

Why close this? I haven't had the chance to review it yet, but it seemed like a good idea.

**Comment by fryn** [comment]
I unintentionally closed it by deleting the branch in my fork of the repo. Since I've been making these changes using only the web interface, I don't have a local copy of the branch to re-push, which is required to re-open the request. Feel free to review and/or take the changes despite the pull request being closed.

**Comment by LeaVerou** [comment]
Thanks, and sorry for taking so pathetically long to review :(
Btw, have you tested through the dev tools that it actually helps avoid reflows? Perhaps browsers are smart enough not to reflow if the CSS doesn't actually change, but probably not.

**Comment by fryn** [comment]
I have tested, and it definitely helps avoid reflows, especially when the CSS contains transitions or animations that don't need prefixing (which is always the case in Firefox). Setting the text content of a stylesheet back to itself actually causes all animations to restart.

**Pull request closed without merging**
