### PR TITLE
Add info on data-noprefix to FAQ

### PR DESCRIPTION
**Pull request by johtso**
I assume the FAQ was the right place to put it, as there's no documentation as such (usage is so simple it's not really needed!).

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hi, thanks! `<style>` accepts `data-noprefix` too.

**Comment by johtso** [comment]
@LeaVerou ah, was thinking I had probably missed something, added :)

**Comment by LeaVerou** [comment]
Thanks, but now it looks like a sentence is there twice :P

**Comment by johtso** [comment]
You saw nothing!

**Comment by LeaVerou** [comment]
Saw nothing from what? ;-)
Merged, thanks!

**Pull request merged**
