### PR TITLE
Fix issue #109 by @importing CSS as data URIs when printing.

### PR DESCRIPTION
**Pull request by mkantor**
In IE9 swap out prefixed CSS for imported data URIs `onbeforeprint` and restore the regular prefixed CSS `onafterprint` in order to work around [a bug where `@media screen` styles were being applied to print media](https://github.com/LeaVerou/prefixfree/issues/109).

[Some tests are available here](http://mkantor.github.com/prefixfree-tests/tests/?prefixfree-url=http%3A%2F%2Fmkantor.github.com%2Fprefixfree-tests%2Fprefixfree.js). Compare this to [the same tests run with a version of -prefix-free without the changes from this pull request](http://mkantor.github.com/prefixfree-tests/tests/?prefixfree-url=http%3A%2F%2Fleaverou.github.com%2Fprefixfree%2Fprefixfree.js) (print the pages with IE9 and compare the results).

### CODE REVIEW

**Comment by mkantor** [comment]
To get GitHub to do its fancy cross-reference thing: this fixes #109.

**Comment by mkantor** [comment]
@LeaVerou I realize you're very busy and that I submitted this pull request ages ago, but is there anything I can do to help get this reviewed? I'd even be satisfied if the answer is "now that IE10 exists forget about this bug".

**Comment by Kompwu** [comment]
@mkantor This project isn't really maintained anymore...

**Comment by LeaVerou** [comment]
@Kompwu you felt the need to comment on a PR from 2013 to say that the project is not maintained anymore?! LOL, what a weird thing to do.

@mkantor Sorry for the huge delay in getting back to you, I guess this slipped through the cracks! Thank you so much for contributing to prefixfree! At this point, I would be wary of adding this much code to support something in IE9, its market share is 0.13% globally, so I'm gonna close this. Sorry about that!

**Pull request closed without merging**
